[package]
name = "prek-pty"
version = "0.0.1"
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
rustix = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
